### ISSUE TITLE
Prompt questions

### ISSUE THREAD

**Issue by HuanyiZheng** [lehduong/OneDiffusion#14]
Can you give an example of how to do image inpainting? Please give the inference code of the example

**Comment by lehduong** [comment]
There is an example of inpainting in [huggingface space](https://huggingface.co/spaces/lehduong/OneDiffusion) (2nd page).

For inference code, just follow the pipeline [in this line](https://github.com/lehduong/OneDiffusion/blob/6a64303695bea9209d87a2943b329705e4925207/inference.py#L33). Just change the condition image and the prompt.

The model currently supports gray (128, 128, 128) and black (0,0,0) mask.
